insert into producent (nazwa, kraj) values ('Canon', 'Japonia');
insert into producent (nazwa, kraj) values ('Chadex', 'Chiny');
insert into producent (nazwa, kraj) values ('Canon', 'Japonia');
insert into producent (nazwa, kraj) values ('Nixon', 'Niemcy');
insert into producent (nazwa, kraj) values ('Nixon', 'Niemcy');
insert into producent (nazwa, kraj) values ('Canon', 'Japonia');
insert into producent (nazwa, kraj) values ('Canon', 'Japonia');
insert into producent (nazwa, kraj) values ('Sony', 'Chiny');
insert into producent (nazwa, kraj) values ('Canon', 'Japonia');
insert into producent (nazwa, kraj) values ('Nixon', 'Niemcy');
insert into producent (nazwa, kraj) values ('Sony', 'Chiny');
insert into producent (nazwa, kraj) values ('Canon', 'Japonia');
insert into producent (nazwa, kraj) values ('Sony', 'Chiny');
insert into producent (nazwa, kraj) values ('Aparatex', 'Polska');
insert into producent (nazwa, kraj) values ('Chadex', 'Chiny');

insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Canon EF', 1.4, 16);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Canon ZF', 1.8, 27);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Canon ZF', 1.8, 27);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Canon ZF', 1.8, 27);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Tessar T', 1.2, 32);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Tessar T', 1.2, 32);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Tessar T', 1.2, 32);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Canon EF', 1.4, 16);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('TAMRON', 1.6, 23);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Canon EF', 1.4, 16);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Canon EF', 1.4, 16);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('TAMRON', 1.6, 23);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Canon EF', 1.4, 16);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('Tessar T', 1.2, 32);
insert into obiektyw (model, minPrzeslona, maxPrzeslona) values ('TAMRON', 1.6, 23);

insert into matryca (przekatna, rozdzielczosc, typ) values (15.6, 24.1, 'Foveon');
insert into matryca (przekatna, rozdzielczosc, typ) values (17.2, 24.1, 'Foveon');
insert into matryca (przekatna, rozdzielczosc, typ) values (18.2, 24.1, 'Foveon');
insert into matryca (przekatna, rozdzielczosc, typ) values (20.2, 24.1, 'CCD');
insert into matryca (przekatna, rozdzielczosc, typ) values (18.4, 24.1, 'CCD');
insert into matryca (przekatna, rozdzielczosc, typ) values (15.6, 24.1, 'Foveon');
insert into matryca (przekatna, rozdzielczosc, typ) values (15.4, 24.1, 'Foveon');
insert into matryca (przekatna, rozdzielczosc, typ) values (15.2, 24.1, 'CMOS');
insert into matryca (przekatna, rozdzielczosc, typ) values (17.4, 24.1, 'CMOS');
insert into matryca (przekatna, rozdzielczosc, typ) values (18.2, 24.1, 'CMOS');
insert into matryca (przekatna, rozdzielczosc, typ) values (15.8, 24.1, 'CMOS');
insert into matryca (przekatna, rozdzielczosc, typ) values (17.6, 24.1, 'CCD');
insert into matryca (przekatna, rozdzielczosc, typ) values (16.2, 24.1, 'CCD');
insert into matryca (przekatna, rozdzielczosc, typ) values (14.8, 24.1, 'Foveon');
insert into matryca (przekatna, rozdzielczosc, typ) values (16.4, 24.1, 'Foveon');

insert into aparat (model, producent, matryca, obiektyw, typ) values ('Canon 4D', 1, 100, 1, 'lustrzanka');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Chadex 5UF', 2, 101, 2, 'lustrzanka');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Canon 52E', 3, 102, 3, 'kompaktowy');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Nixon 21', 4, 103, 4, 'inny');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Nixon 32', 5, 104, 5, 'profesjonalny');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Canon 6F', 6, 105, 6, 'kompaktowy');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Canon 7F', 7, 106, 7, 'lustrzanka');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Sony Ultra 23F', 8, 107, 8, 'lustrzanka');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Canon 231D', 9, 108, 9, 'inny');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Nixon', 10, 109, 10, 'profesjonalny');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Sony 13T', 11, 110, 11, 'profesjonalny');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Canon 2CD', 12, 111, 12, 'kompaktowy');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Sony 9U', 13, 112, 13, 'lustrzanka');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Aparetex 1GEN', 14, 113, 14, 'lustrzanka');
insert into aparat (model, producent, matryca, obiektyw, typ) values ('Chadex X', 15, 114, 15, 'kompaktowy');
